#!/bin/bash

# Deployment helper for Vercel
echo "=== Vercel Deployment Setup ==="
echo ""
echo "To fix the build error, you need to add these environment variables to Vercel:"
echo ""
echo "1. Go to your Vercel project dashboard"
echo "2. Navigate to Settings → Environment Variables"
echo "3. Add the following variables:"
echo ""
echo "FIREBASE_PROJECT_ID=your-project-id"
echo "FIREBASE_CLIENT_EMAIL=firebase-adminsdk-xxxxx@your-project-id.iam.gserviceaccount.com"
echo "FIREBASE_PRIVATE_KEY_BASE64=base64-encoded-private-key"
echo ""
echo "### Getting the Base64 Private Key"
echo ""
echo "To get the base64 encoded private key from your JSON service account file:"
echo ""
echo "cat path/to/your-service-account.json | jq -r .private_key | base64"
echo ""
echo "Or encode the private key directly:"
echo "echo \"-----BEGIN PRIVATE KEY-----"
echo "..."
echo "-----END PRIVATE KEY-----\" | base64"
echo ""
echo "After adding the environment variables, redeploy:"
echo "vercel --prod"
